### ISSUE TITLE
样图是怎么跑出来的

### ISSUE THREAD

**Issue by Aliang-CN** [ykk648/AnimateDiff#1]
hi,
     您好,我在复现结果,发现图不太对,可以帮忙分析一下问题出现在哪里吗?

**Comment by Aliang-CN** [comment]
![0-best-quality,-masterpiece,-1girl,-looking-at-viewer,-blurry-background,-upper](https://github.com/ykk648/AnimateDiff/assets/35071040/8d9d11a7-71c7-454c-a2b5-e8a1bd6ca17a)

**Comment by ykk648** [comment]
两个超参 https://github.com/ykk648/AnimateDiff/blob/5f4adb8c1b6729bc6511b217f69aee825151554a/animatediff/pipelines/pipeline_animation.py#L354

https://github.com/ykk648/AnimateDiff/blob/5f4adb8c1b6729bc6511b217f69aee825151554a/animatediff/pipelines/pipeline_animation.py#L439

你这个效果看从第一帧开始添加了过多噪声，按照代码不会这样的，看下每一帧的init_alpha是多少

**Comment by zhanghongyong123456** [comment]
> 两个超参
> 
> https://github.com/ykk648/AnimateDiff/blob/5f4adb8c1b6729bc6511b217f69aee825151554a/animatediff/pipelines/pipeline_animation.py#L354
> 
> https://github.com/ykk648/AnimateDiff/blob/5f4adb8c1b6729bc6511b217f69aee825151554a/animatediff/pipelines/pipeline_animation.py#L439
> 
> 你这个效果看从第一帧开始添加了过多噪声，按照代码不会这样的，看下每一帧的init_alpha是多少

请问这两个超参数控制什么的，是控制视频运动幅度大小的吗，如何提高运动幅度的

**Comment by ykk648** [comment]
@zhanghongyong123456 `denoise_strength`与sd-webui一致，减少采样次数，`truncate_alpha`是init_image采样latent与noise的加权weight，截断是为了保证生成质量

**Comment by zhanghongyong123456** [comment]
> @zhanghongyong123456 `denoise_strength`与sd-webui一致，减少采样次数，`truncate_alpha`是init_image采样latent与noise的加权weight，截断是为了保证生成质量

谢谢您的及时回复，测试了一些样例，生成的视频，变化不是太大，有没有什么参数能调节运动幅度（或者说是变化幅度），比如这个demo的样子
https://twitter.com/pika_labs/status/1678892871670464513

**Comment by ykk648** [comment]
现在没有开源能做到跟gen2 pikalabs一样的效果，从animatediff的技术实现上看无法实现很好的I2V，魔改之后train一下或许可以，有思路但目前没有实现的动力 😊

**Comment by Aliang-CN** [comment]
> 现在没有开源能做到跟gen2 pikalabs一样的效果，从animatediff的技术实现上看无法实现很好的I2V，魔改之后train一下或许可以，有思路但目前没有实现的动力 blush

我测试过pika，这个的确是目前文生视频，或者图生视频的天花板啊，效果是真的好！
