### ISSUE TITLE
about  update？

### ISSUE THREAD

**Issue by zhanghongyong123456** [ykk648/AnimateDiff#10]
Is it updated with new model picture driven video, or is it just updated with new model text driven video?

**Comment by ykk648** [comment]
animatediff v2 is a bigger text2video model with more params(unet mid block with motion module injection

**Comment by zhanghongyong123456** [comment]
> animatediff v2 is a bigger text2video model with more params(unet mid block with motion module injection

when i   test  animate.py,I  find  a  issues,
use   your's   ip_adapter file,have this error,
![image](https://github.com/ykk648/AnimateDiff/assets/48466610/b111f2f6-94f3-42ef-bbc6-62f431c196d2)
replace   https://github.com/tencent-ailab/IP-Adapter/tree/main/ip_adapter, have this error
![image](https://github.com/ykk648/AnimateDiff/assets/48466610/48c6dd70-aaf3-43f5-931b-ef92cbe18fdc)

**Comment by zhanghongyong123456** [comment]
> > animatediff v2 is a bigger text2video model with more params(unet mid block with motion module injection
> 
> when i test animate.py,I find a issues, use your's ip_adapter file,have this error, ![image](https://user-images.githubusercontent.com/48466610/266950702-b111f2f6-94f3-42ef-bbc6-62f431c196d2.png) replace https://github.com/tencent-ailab/IP-Adapter/tree/main/ip_adapter, have this error ![image](https://user-images.githubusercontent.com/48466610/266950403-48c6dd70-aaf3-43f5-931b-ef92cbe18fdc.png)

I  can't  find  "reference"   controlnet model?
![image](https://github.com/ykk648/AnimateDiff/assets/48466610/dcf239f1-9dcb-44eb-9928-e41ce2ce6a7f)
from https://huggingface.co/lllyasviel  page ,I don't know  which  model  need download?

**Comment by ykk648** [comment]
1. you need pytorch2.0
2. if you use this [config](https://github.com/ykk648/AnimateDiff/blob/main/configs/prompts/AstronautMars.yaml), you need download `control_v11p_sd15_canny` pth/ckpt  from huggingface
3. reference mode do not need any controlnet model if you name the `controlnet_name` to `reference`

**Comment by zhanghongyong123456** [comment]
> 1. you need pytorch2.0
> 2. if you use this [config](https://github.com/ykk648/AnimateDiff/blob/main/configs/prompts/AstronautMars.yaml), you need download `control_v11p_sd15_canny` pth/ckpt  from huggingface
> 3. reference mode do not need any controlnet model if you name the `controlnet_name` to `reference`

about  pytorch version,i chage code  about  https://github.com/tencent-ailab/IP-Adapter/commit/74c1f7c7a7749b52efb883198ff0755d68e160de
![image](https://github.com/ykk648/AnimateDiff/assets/48466610/936a9f89-878b-44f2-b9c9-6e07618c154c)
when  i   run animate.py  RuntimeError: CUDA out of memory.  but  My cuda  48G
RuntimeError: CUDA out of memory. Tried to allocate 16.00 GiB (GPU 0; 47.45 GiB total capacity; 24.62 GiB already allocated; 4.10 GiB free; 41.47 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF

![image](https://github.com/ykk648/AnimateDiff/assets/48466610/9335e2db-19f9-4cc1-b440-61cda41df412)

**Comment by ykk648** [comment]
torch                     2.0.1
xformers                  0.0.20
it works well

**Comment by zhanghongyong123456** [comment]
> 

OK   I  try it
