### ISSUE TITLE
虽然能图像驱动视频，但是无法加载lora了

### ISSUE THREAD

**Issue by MtYCNN** [ykk648/AnimateDiff#12]
temp_name += "_" + layer_infos.pop(0)
IndexError: pop from empty list

**Comment by ykk648** [comment]
https://github.com/ykk648/AnimateDiff/commit/926806dd8999e0b63bc6a27f81d6f39e9cabf1cf

测试可以加载lora

**Comment by MtYCNN** [comment]
> [926806d](https://github.com/ykk648/AnimateDiff/commit/926806dd8999e0b63bc6a27f81d6f39e9cabf1cf)
> 
> 测试可以加载lora

似乎还是不行,我直接用的您昨天更新的源码：

AttributeError: 'CLIPTextModel' object has no attribute 'cond_stage_model'

Traceback (most recent call last):
  File "animate.py", line 235, in <module>
    main(args)
  File "animate.py", line 143, in main
    pipeline = convert_lora(pipeline, state_dict, alpha=model_config.lora_alpha)
  File "/mnt/workspace/user26/AnimateDiff/animatediff/utils/convert_lora_safetensor_to_diffusers.py", line 62, in convert_lora
    temp_name += "_" + layer_infos.pop(0)
IndexError: pop from empty list

**Comment by ykk648** [comment]
第一个报错：
clip                      1.0
open-clip-torch           2.20.0

第二个，我怀疑是和你用的lora模型有关，这是lora转diffusers失败，这部分代码与diffusers/原repo都是一致的，建议换lora或者断点调试
ref https://github.com/huggingface/diffusers/issues/4616

**Comment by MtYCNN** [comment]
> clip 1.0
> open-clip-torch 2.20.0

clip、open-clip-torch     感觉原工程没有调用过这俩依赖把，我直接安装发现自动把torch什么的都给升级到最高了。。。
