### ISSUE TITLE
init_image cannot be set to none in the config file

### ISSUE THREAD

**Issue by haohantianchen** [ykk648/AnimateDiff#16]
In this repo I see that init_image is supposed to be none, but in practice an error occurs when init_image is set to none

**Comment by ykk648** [comment]
I'm focused on I2V mission, so init_image is necessary in the config file, if you want do origin animatediff infer without init_image, set the denoise_strength to 1 , and set https://github.com/ykk648/AnimateDiff-I2V/blob/0842585aa4fd41e25542979b5110701dca923870/animatediff/pipelines/stablediffusion_animatediff_pipeline.py#L406 to None.

**Comment by haohantianchen** [comment]
thanks

**Comment by haohantianchen** [comment]
it seems that the current controlnet can only control the first frame of generated video？Not the whole video?

**Comment by ykk648** [comment]
@haohantianchen  multi-controlnet in new version already have been tested, I will push it asap
