### ISSUE TITLE
Improving Video Quality using Ebsynth?

### ISSUE THREAD

**Issue by hajiarab1988** [ykk648/AnimateDiff#17]
Dear @ykk648 

I've been following your impressive work on AnimateDiff, and I'm interested in enhancing the video quality it generates. Have you considered integrating Ebsynt for this purpose? I'd love to hear your thoughts on this potential improvement and any suggestions you may have.

Thanks,

**Comment by ykk648** [comment]
Hi there, Ebsynth is a image interplation method as same as RIFE and others, it may became one post-process procedure to increase frame consistence, but it's not an algorithm releated to SD.
I may add it in the future, but now I'm focus on improve animatediff performence itself.

**Comment by hajiarab1988** [comment]
Hi and thank you for your respound.
here is my results using Ebsynth:
the source gif file i generated using your greate job: 
https://drive.google.com/file/d/1NPMOC3k6tUdjV14CzjIEnuC31VP9tJ8S/view?usp=sharing

and the output file after a simple Ebsynth process: 
https://drive.google.com/file/d/1XO7Z8r7GV6uXK0WS4eFGjAX6AtgYamlJ/view?usp=sharing
