### ISSUE TITLE
App.py doesn't work

### ISSUE THREAD

**Issue by Ainaemaet** [ykk648/AnimateDiff#2]
Hello, I am having the same issue with all of the AnimateDiff repos I've tried including this one. Nobody seems to be interested in helping on any of the others (perhaps just too many) so I'm hoping you might be able to help 🙏

So inference runs fine via the provided samples codes and I get proper output in the 'output' folder,

but when trying to run 'python app.py' I get the following error:
`python app.py Traceback (most recent call last): File "/home/myusername/ML/MC/AnimateDiff/app.py", line 651, in <module> demo = ui() File "/home/myusername/ML/MC/AnimateDiff/app.py", line 636, in ui generate_tab_ui() File "/home/myusername/ML/MC/AnimateDiff/app.py", line 475, in generate_tab_ui stable_diffusion_dropdown, motion_module_dropdown, checkpoint_dropdown = base_model_selection_ui() File "/home/myusername/ML/MC/AnimateDiff/app.py", line 416, in base_model_selection_ui value=controller.checkpoints_list[0], IndexError: list index out of range`

Running in anaconda WSL2 Ubuntu20.04 if that helps.

Really looking forwards to getting this working!!! <3

**Comment by ykk648** [comment]
This file only have 328 lines, https://github.com/guoyww/AnimateDiff/blob/53c63ad8391d7095ab5364c13b4aa3a7d183dac5/app.py#L328, I can't find your codes in original repo https://github.com/search?q=repo%3Aguoyww%2FAnimateDiff+controller.checkpoints_list&type=code

**Comment by Ainaemaet** [comment]
Ver sorry about that. I had a few versions downloaded and got them confused. I was trying to run this fork from hoalarius https://github.com/hoalarious/AnimateDiff and I get the error. 

Does this repo support longer generation code and I2V like that one?

**Comment by ykk648** [comment]
no plan for now, longer video means concatation of different infer results, less continuity is foreseeable.
