### ISSUE TITLE
not working extension

### ISSUE THREAD

**Issue by Rubenacp** [ykk648/AnimateDiff#20]
Hi, 
I added the extension to automatic1111, but it does not work. This fork can work as extension?

**Comment by ykk648** [comment]
nope, this repo was wrote by diffusers, which is diffierent from webui, you can refer https://github.com/continue-revolution/sd-webui-animatediff

**Comment by Rubenacp** [comment]
Yes I use that extension, but I was looking for one that makes image 2 video, thank you
