### ISSUE TITLE
In each ControlNet module, init_image can only be a single image.

### ISSUE THREAD

**Issue by haohantianchen** [ykk648/AnimateDiff#21]
Hello, in each controlnet_n, each init_image can only be a single image. Suppose I want to infer a 16-frame video using control_v11p_sd15_canny. According to the current code implementation, I can only set controlnet_1 through controlnet_16, for a total of 16 controlnet modules. This places a very high demand on GPU memory, as I'm using 16 frames as an example. Is there a possibility to improve this part so that for the same type of controlnet function, such as control_v11p_sd15_canny, it can directly read a list of init_image, and similarly, controlnet_frame also reads a corresponding list, allowing Canny to use only one controlnet module?

**Comment by ykk648** [comment]
Hi there, sure it can do so, but it's not what I'm targeting now, you can mod the codes by your needs. :)

**Comment by haohantianchen** [comment]
Thank you!
