### ISSUE TITLE
feature request: support dreambooth 

### ISSUE THREAD

**Issue by EmmaThompson123** [ykk648/AnimateDiff#22]
In original animatediff repo, it load dreambooth model weight in `def load_weights`, but here it seems not do this in `def pipeline_loading`

**Comment by ykk648** [comment]
ref https://github.com/ykk648/AnimateDiff-I2V/blob/b87f92f1300892e0664be56a8c945385b1a99b14/scripts/animate.py#L107
 model_config.base is equal to dreambooth model
