### ISSUE TITLE
Any plans to add SDXL version

### ISSUE THREAD

**Issue by julkaztwittera** [ykk648/AnimateDiff#23]
Hi,
great work!
Are you also planning to add SDXL version?

**Comment by ykk648** [comment]
yeah, but I'm busy to do some digitalhuman code development these days, SDXL may be better than SD1.5, but the `better controllability and quality` one is more attractive https://github.com/guoyww/AnimateDiff#next

**Comment by JoshonSmith** [comment]
looking forward to sdxl version！

**Comment by ykk648** [comment]
Don't have time to port the SDXL version anymore.

**Comment by JoshonSmith** [comment]
oh! 
its sad!

**Comment by JoshonSmith** [comment]
oh! 
its sad!
