### ISSUE TITLE
how to train animatediff with image

### ISSUE THREAD

**Issue by pokameng** [ykk648/AnimateDiff#27]
@ykk648 
你好 ，请问目前的animatediff支持基于image训练吗？我看到animatediff是text2video，我想试试是否可以基于image训练，或者说，您现在发布的这个版本，是否支持基于image 训练。
我尝试把ip-adaopter的部分迁移到animatediff，但是效果却不行，并且我还打印了ip-adapter的imageprojModel的梯度，始终为nan。
不知道animatediff是否可以魔改为prompt+image。

**Comment by ykk648** [comment]
肯定是可以的，我这边不支持，很多人在这个方向做过，比如 https://github.com/CiaraStrawberry/Temporal-Image-AnimateDiff/tree/simpleCondition

**Comment by pokameng** [comment]
好的&nbsp; 谢谢！！
话说可否再分享几个相关的呢？我之前找的但是没发现类似的


繁华落尽
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "ykk648/AnimateDiff-I2V"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年12月25日(星期一) 上午9:58
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [ykk648/AnimateDiff-I2V] how to train animatediff with image (Issue #27)





 
肯定是可以的，我这边不支持，很多人在这个方向做过，比如 https://github.com/CiaraStrawberry/Temporal-Image-AnimateDiff/tree/simpleCondition
