### ISSUE TITLE
关于人物不动的问题

### ISSUE THREAD

**Issue by Aliang-CN** [ykk648/AnimateDiff#4]
![0-a-young-man,-25-year-old,-black_hair,-buttons,-male_focus,-shirt-(masterpiece:1 2,-best](https://github.com/ykk648/AnimateDiff/assets/35071040/a086eec0-554f-4782-a999-ed9485ea9c9a)
 您好！
     代码，我没有修改过，我发现我做出来的人物基本不动。
   

配置如下：

InitImageYoimiya:
  path: models/DreamBooth_LoRA/darkSushiMixMix_225D.safetensors
  base: models/DreamBooth_LoRA/flynn_anything_000001.safetensors
  init_image: configs/prompts/test2.jpg
  motion_module:
  - models/Motion_Module/mm_sd_v14.ckpt
  - models/Motion_Module/mm_sd_v15.ckpt
  steps: 25
  guidance_scale: 7.5
  lora_alpha: 0.8
  prompt:
  - a young man, 25-year-old, black_hair, buttons, male_focus, shirt (masterpiece:1.2,
    best quality), (real picture, intricate details), boating by the river
  n_prompt:
  - (worst quality, low quality, blurry:1.66), (bad hand:1.4), watermark, (greyscale:0.88),
    multiple limbs, (deformed fingers, bad fingers:1.2), (ugly:1.3), monochrome, horror,
    geometry, bad anatomy, bad limbs, (Blurry pupil), (bad shading), error, bad composition,
    Extra fingers, strange fingers, Extra ears, extra leg, bad leg, disability, Blurry
    eyes, bad eyes, Twisted body, confusion, (bad legs:1.3)
  random_seed:
  - 6484192963163605314

**Comment by ykk648** [comment]
正常，目前只能做到这个程度

**Comment by Aliang-CN** [comment]
> 正常，目前只能做到这个程度

我看你的demo，效果还可以哈

**Comment by Aliang-CN** [comment]
> 正常，目前只能做到这个程度

大佬，是怎么做到的

**Comment by ykk648** [comment]
https://github.com/ykk648/AnimateDiff/issues/1#issuecomment-1670603810
