### ISSUE TITLE
reconstructed code has some bugs

### ISSUE THREAD

**Issue by zzningxp** [ykk648/AnimateDiff#6]
BUG1:
animatediff/models/unet_2d_blocks.py line 543 Downsample3D should be Downsample2D

BUG2:
old model structure changed:
File "animatediff/models/unet_2d_condition.py", line 650, in fn_recursive_attn_processor
    module.set_processor(processor.pop(f"{name}.processor"))
KeyError: 'down_blocks.0.attentions.0.transformer_blocks.0.attn1.processor'

**Comment by zzningxp** [comment]
Load pretrain model into unet changed:
From:
```
        config["down_block_types"] = [
            "CrossAttnDownBlock3D",
            "CrossAttnDownBlock3D",
            "CrossAttnDownBlock3D",
            "DownBlock3D"
        ]
        config["up_block_types"] = [
            "UpBlock3D",
            "CrossAttnUpBlock3D",
            "CrossAttnUpBlock3D",
            "CrossAttnUpBlock3D"
        ]
```
To:
```
        config["down_block_types"] = [
            "CrossAttnDownBlock2D",
            "CrossAttnDownBlock2D",
            "CrossAttnDownBlock2D",
            "DownBlock2D"
        ]
        config["up_block_types"] = [
            "UpBlock2D",
            "CrossAttnUpBlock2D",
            "CrossAttnUpBlock2D",
            "CrossAttnUpBlock2D"
        ]
```

**Comment by ykk648** [comment]
will be fixed later

**Comment by ykk648** [comment]
check https://github.com/ykk648/AnimateDiff/commit/bdfd4578f4db6f148d7533f4ddb209c6b4317c39

**Comment by zzningxp** [comment]
Good!
Also, 
new version performance declines when video frame is set to 24.
before reconstruction, 16 and 24 both work. after reconstruction, 16 works while 24 declines.

And the background of new version flickers more.

**Comment by zzningxp** [comment]
While, if L is not divisible by 8, error will be raised. if L is divisible by 8 but not divisible by 16, like 24, the result is bad. 
If L is divisible by 16, the result is good, however, the result video is obviously divided into subdivisions of 16 frames...

**Comment by ykk648** [comment]
Have you modified the param in https://github.com/ykk648/AnimateDiff/blob/bdfd4578f4db6f148d7533f4ddb209c6b4317c39/configs/inference/inference.yaml#L22 ?

**Comment by zzningxp** [comment]
OK.

video_length should not be set larger than 24, because of the limited pretrained motion module. Is this correct?

**Comment by ykk648** [comment]
that's correct
