### ISSUE TITLE
out of memory

### ISSUE THREAD

**Issue by Neph0s** [ykk648/AnimateDiff#8]
when i run the following command on a RTX 3090
`python -m scripts.animate --config configs/prompts/13-my.yaml`

get OOM error:

torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 23.96 GiB (GPU 0; 23.70 GiB total capacity; 7.32 GiB already allocated; 13.40 GiB free; 8.67 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF

my config file is: 

`InitImageYoimiya:
  base: "models/DreamBooth_LoRA/fiveNutsMixedMix_v10.safetensors"
  path: "models/DreamBooth_LoRA/hanfuTang_v32.safetensors"
  init_image: "configs/prompts/xry.jpg"

  motion_module:
    - "models/Motion_Module/mm_sd_v14.ckpt"
    - "models/Motion_Module/mm_sd_v15.ckpt"

  IPAdapter: false
  steps:          25
  guidance_scale: 7.5
  lora_alpha: 0.8
  denoise_strength: 0.6
  init_alpha: 0.1
  alpha_step: 0.01
  truncate_alpha: 0.05
  ip_strength: 1

  prompt:
    - "1girl, The wind blew up her hair and blew away the flowers"

  n_prompt:
    - "NSFW, lr, nsfw,(sketch, duplicate, ugly, huge eyes, ..."`

I wonder how it tries to allocate 24G memory

**Comment by ykk648** [comment]
I'm using A100 so never concern about GPU mem, you can try use `.to('cuda', dtype=torch.float16)` decrease the mem.
Now my local version is far from this repo (add controlnet etc.) , don't have time to deal with GPU mem issue.
Soon I will push latested version and stop develop, after that, I may review this issue and solve it.

**Comment by ykk648** [comment]
check https://github.com/ykk648/AnimateDiff/commit/f1b0465e1c84c9037e3e4cb523758150e2861ecb, I have tested float16 mode, GPU mem usage is about 13G
