### ISSUE TITLE
About results

### ISSUE THREAD

**Issue by Johanan528** [ykk648/AnimateDiff#9]
Why isn't the generated result an animation, but completely static?

**Comment by volcverse** [comment]
Same problem. Could you please tell me how you solve this?

**Comment by ykk648** [comment]
Plz provide a more detailed description, you mean running provided demo and find that generated `sample.gif` have totally same 16 frames? OR the motion is too small to see？

**Comment by Johanan528** [comment]
I extracted each frame of the gif file and it is indeed different. However, the sampling result is that the gif file does not move at all. In addition, I would like to ask you about the experimental parameters of yoimiya. Can you share the .yml file? I did not get the results in the readme.md
